openapi: 3.0.0

info:
    title: Ecom App
    description: LCO - a course to create API for ecom store
    version: 1.0.1
    contact:
        email: dharmjeetvaishnav@gmail.com
        url: "https://dharmjeet.com"

servers:
    - url: "{protocol}://localhost:8000/api/{version}"
      description: for local host
      variables:
          version:
              enum:
                  - v1
                  - v2
              default: v1
          protocol:
              enum:
                  - http
                  - https
              default: http

components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: token
        BearerAuth:
            type: http
            scheme: bearer

paths:
    /:
        get:
            tags:
                - Home
            summary: returns a greet message from LCO
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: string
                                example: "mystring"
                400:
                    description: Bad Request
                500:
                    description: Internal server error

    /signup:
        post:
            tags:
                - User
            summary: signup page
            consumes:
                - application/json
            produces:
                - application/json
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                email:
                                    type: string
                                password:
                                    type: number
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: string
                                example: "mystring"
                400:
                    description: Bad Request
                500:
                    description: Internal server error
